# Generated by Django 4.1 on 2022-11-14 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 11, 45, 56, 49299)),
        ),
    ]
